// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// group_tri_mean_dgc_cpp
NumericMatrix group_tri_mean_dgc_cpp(const S4& cell_by_gene, const IntegerVector& group, int group_count);
RcppExport SEXP _SpatialESS_group_tri_mean_dgc_cpp(SEXP cell_by_geneSEXP, SEXP groupSEXP, SEXP group_countSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type cell_by_gene(cell_by_geneSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type group_count(group_countSEXP);
    rcpp_result_gen = Rcpp::wrap(group_tri_mean_dgc_cpp(cell_by_gene, group, group_count));
    return rcpp_result_gen;
END_RCPP
}
// aggregate_group_support_csr_cpp
DataFrame aggregate_group_support_csr_cpp(const NumericVector& offsets, const IntegerVector& neighbors, const NumericVector& weights, const IntegerVector& group, int group_count, double max_group_pairs);
RcppExport SEXP _SpatialESS_aggregate_group_support_csr_cpp(SEXP offsetsSEXP, SEXP neighborsSEXP, SEXP weightsSEXP, SEXP groupSEXP, SEXP group_countSEXP, SEXP max_group_pairsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type offsets(offsetsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type neighbors(neighborsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type group_count(group_countSEXP);
    Rcpp::traits::input_parameter< double >::type max_group_pairs(max_group_pairsSEXP);
    rcpp_result_gen = Rcpp::wrap(aggregate_group_support_csr_cpp(offsets, neighbors, weights, group, group_count, max_group_pairs));
    return rcpp_result_gen;
END_RCPP
}
// score_cellchat_group_support_cpp
List score_cellchat_group_support_cpp(const NumericMatrix& average, const IntegerVector& sender_group, const IntegerVector& receiver_group, const NumericVector& supported_edges, const NumericVector& sum_spatial_weight, const NumericVector& mean_spatial_weight, const IntegerMatrix& ligand_indices, const IntegerMatrix& receptor_indices, const IntegerMatrix& co_a_indices, const IntegerMatrix& co_i_indices, const IntegerMatrix& agonist_indices, const IntegerMatrix& antagonist_indices, const LogicalVector& has_agonist, const LogicalVector& has_antagonist, double Kh, double n_power, double max_output_records);
RcppExport SEXP _SpatialESS_score_cellchat_group_support_cpp(SEXP averageSEXP, SEXP sender_groupSEXP, SEXP receiver_groupSEXP, SEXP supported_edgesSEXP, SEXP sum_spatial_weightSEXP, SEXP mean_spatial_weightSEXP, SEXP ligand_indicesSEXP, SEXP receptor_indicesSEXP, SEXP co_a_indicesSEXP, SEXP co_i_indicesSEXP, SEXP agonist_indicesSEXP, SEXP antagonist_indicesSEXP, SEXP has_agonistSEXP, SEXP has_antagonistSEXP, SEXP KhSEXP, SEXP n_powerSEXP, SEXP max_output_recordsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type average(averageSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type sender_group(sender_groupSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type receiver_group(receiver_groupSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type supported_edges(supported_edgesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type sum_spatial_weight(sum_spatial_weightSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type mean_spatial_weight(mean_spatial_weightSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type ligand_indices(ligand_indicesSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type receptor_indices(receptor_indicesSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type co_a_indices(co_a_indicesSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type co_i_indices(co_i_indicesSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type agonist_indices(agonist_indicesSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type antagonist_indices(antagonist_indicesSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type has_agonist(has_agonistSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type has_antagonist(has_antagonistSEXP);
    Rcpp::traits::input_parameter< double >::type Kh(KhSEXP);
    Rcpp::traits::input_parameter< double >::type n_power(n_powerSEXP);
    Rcpp::traits::input_parameter< double >::type max_output_records(max_output_recordsSEXP);
    rcpp_result_gen = Rcpp::wrap(score_cellchat_group_support_cpp(average, sender_group, receiver_group, supported_edges, sum_spatial_weight, mean_spatial_weight, ligand_indices, receptor_indices, co_a_indices, co_i_indices, agonist_indices, antagonist_indices, has_agonist, has_antagonist, Kh, n_power, max_output_records));
    return rcpp_result_gen;
END_RCPP
}
// radius_graph_csr_cpp
List radius_graph_csr_cpp(const NumericMatrix& coords, const IntegerVector& sample, const IntegerVector& compartment, double radius, bool same_compartment, std::string weight_method, double weight_scale, bool store_distance, double max_edges);
RcppExport SEXP _SpatialESS_radius_graph_csr_cpp(SEXP coordsSEXP, SEXP sampleSEXP, SEXP compartmentSEXP, SEXP radiusSEXP, SEXP same_compartmentSEXP, SEXP weight_methodSEXP, SEXP weight_scaleSEXP, SEXP store_distanceSEXP, SEXP max_edgesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type compartment(compartmentSEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< bool >::type same_compartment(same_compartmentSEXP);
    Rcpp::traits::input_parameter< std::string >::type weight_method(weight_methodSEXP);
    Rcpp::traits::input_parameter< double >::type weight_scale(weight_scaleSEXP);
    Rcpp::traits::input_parameter< bool >::type store_distance(store_distanceSEXP);
    Rcpp::traits::input_parameter< double >::type max_edges(max_edgesSEXP);
    rcpp_result_gen = Rcpp::wrap(radius_graph_csr_cpp(coords, sample, compartment, radius, same_compartment, weight_method, weight_scale, store_distance, max_edges));
    return rcpp_result_gen;
END_RCPP
}
// validate_spatial_csr_cpp
List validate_spatial_csr_cpp(const NumericVector& offsets, const IntegerVector& neighbors, const NumericVector& weights, const IntegerVector& sample, const IntegerVector& compartment, bool same_compartment);
RcppExport SEXP _SpatialESS_validate_spatial_csr_cpp(SEXP offsetsSEXP, SEXP neighborsSEXP, SEXP weightsSEXP, SEXP sampleSEXP, SEXP compartmentSEXP, SEXP same_compartmentSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type offsets(offsetsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type neighbors(neighborsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type compartment(compartmentSEXP);
    Rcpp::traits::input_parameter< bool >::type same_compartment(same_compartmentSEXP);
    rcpp_result_gen = Rcpp::wrap(validate_spatial_csr_cpp(offsets, neighbors, weights, sample, compartment, same_compartment));
    return rcpp_result_gen;
END_RCPP
}
// materialize_csr_edges_cpp
List materialize_csr_edges_cpp(const NumericVector& offsets, const IntegerVector& neighbors, const NumericVector& weights, const NumericVector& distances);
RcppExport SEXP _SpatialESS_materialize_csr_edges_cpp(SEXP offsetsSEXP, SEXP neighborsSEXP, SEXP weightsSEXP, SEXP distancesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type offsets(offsetsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type neighbors(neighborsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type distances(distancesSEXP);
    rcpp_result_gen = Rcpp::wrap(materialize_csr_edges_cpp(offsets, neighbors, weights, distances));
    return rcpp_result_gen;
END_RCPP
}
// csr_weighted_degree_cpp
NumericVector csr_weighted_degree_cpp(const NumericVector& offsets, const NumericVector& weights);
RcppExport SEXP _SpatialESS_csr_weighted_degree_cpp(SEXP offsetsSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type offsets(offsetsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(csr_weighted_degree_cpp(offsets, weights));
    return rcpp_result_gen;
END_RCPP
}
// aggregate_simple_lr_csr_cpp
List aggregate_simple_lr_csr_cpp(const NumericVector& offsets, const IntegerVector& neighbors, const NumericVector& weights, const NumericVector& ligand_expression, const NumericVector& receptor_expression, const IntegerVector& group, int group_count, double Kh, double n_power, double min_expression, double max_group_pairs);
RcppExport SEXP _SpatialESS_aggregate_simple_lr_csr_cpp(SEXP offsetsSEXP, SEXP neighborsSEXP, SEXP weightsSEXP, SEXP ligand_expressionSEXP, SEXP receptor_expressionSEXP, SEXP groupSEXP, SEXP group_countSEXP, SEXP KhSEXP, SEXP n_powerSEXP, SEXP min_expressionSEXP, SEXP max_group_pairsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type offsets(offsetsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type neighbors(neighborsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type ligand_expression(ligand_expressionSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type receptor_expression(receptor_expressionSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type group_count(group_countSEXP);
    Rcpp::traits::input_parameter< double >::type Kh(KhSEXP);
    Rcpp::traits::input_parameter< double >::type n_power(n_powerSEXP);
    Rcpp::traits::input_parameter< double >::type min_expression(min_expressionSEXP);
    Rcpp::traits::input_parameter< double >::type max_group_pairs(max_group_pairsSEXP);
    rcpp_result_gen = Rcpp::wrap(aggregate_simple_lr_csr_cpp(offsets, neighbors, weights, ligand_expression, receptor_expression, group, group_count, Kh, n_power, min_expression, max_group_pairs));
    return rcpp_result_gen;
END_RCPP
}
// score_simple_lr_edge_cpp
List score_simple_lr_edge_cpp(const IntegerVector& sender, const IntegerVector& receiver, const NumericVector& distance, const NumericVector& spatial_weight, const NumericVector& ligand_expression, const NumericVector& receptor_expression, double Kh, double n_power, double min_expression, double max_output_edges);
RcppExport SEXP _SpatialESS_score_simple_lr_edge_cpp(SEXP senderSEXP, SEXP receiverSEXP, SEXP distanceSEXP, SEXP spatial_weightSEXP, SEXP ligand_expressionSEXP, SEXP receptor_expressionSEXP, SEXP KhSEXP, SEXP n_powerSEXP, SEXP min_expressionSEXP, SEXP max_output_edgesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type sender(senderSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type receiver(receiverSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type distance(distanceSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type spatial_weight(spatial_weightSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type ligand_expression(ligand_expressionSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type receptor_expression(receptor_expressionSEXP);
    Rcpp::traits::input_parameter< double >::type Kh(KhSEXP);
    Rcpp::traits::input_parameter< double >::type n_power(n_powerSEXP);
    Rcpp::traits::input_parameter< double >::type min_expression(min_expressionSEXP);
    Rcpp::traits::input_parameter< double >::type max_output_edges(max_output_edgesSEXP);
    rcpp_result_gen = Rcpp::wrap(score_simple_lr_edge_cpp(sender, receiver, distance, spatial_weight, ligand_expression, receptor_expression, Kh, n_power, min_expression, max_output_edges));
    return rcpp_result_gen;
END_RCPP
}
// score_cellchat_group_records_cpp
NumericVector score_cellchat_group_records_cpp(const NumericMatrix& average, const IntegerVector& sender_group, const IntegerVector& receiver_group, const IntegerVector& record_lr, const IntegerMatrix& ligand_indices, const IntegerMatrix& receptor_indices, const IntegerMatrix& co_a_indices, const IntegerMatrix& co_i_indices, const IntegerMatrix& agonist_indices, const IntegerMatrix& antagonist_indices, const LogicalVector& has_agonist, const LogicalVector& has_antagonist, double Kh, double n_power);
RcppExport SEXP _SpatialESS_score_cellchat_group_records_cpp(SEXP averageSEXP, SEXP sender_groupSEXP, SEXP receiver_groupSEXP, SEXP record_lrSEXP, SEXP ligand_indicesSEXP, SEXP receptor_indicesSEXP, SEXP co_a_indicesSEXP, SEXP co_i_indicesSEXP, SEXP agonist_indicesSEXP, SEXP antagonist_indicesSEXP, SEXP has_agonistSEXP, SEXP has_antagonistSEXP, SEXP KhSEXP, SEXP n_powerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type average(averageSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type sender_group(sender_groupSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type receiver_group(receiver_groupSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type record_lr(record_lrSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type ligand_indices(ligand_indicesSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type receptor_indices(receptor_indicesSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type co_a_indices(co_a_indicesSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type co_i_indices(co_i_indicesSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type agonist_indices(agonist_indicesSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type antagonist_indices(antagonist_indicesSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type has_agonist(has_agonistSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type has_antagonist(has_antagonistSEXP);
    Rcpp::traits::input_parameter< double >::type Kh(KhSEXP);
    Rcpp::traits::input_parameter< double >::type n_power(n_powerSEXP);
    rcpp_result_gen = Rcpp::wrap(score_cellchat_group_records_cpp(average, sender_group, receiver_group, record_lr, ligand_indices, receptor_indices, co_a_indices, co_i_indices, agonist_indices, antagonist_indices, has_agonist, has_antagonist, Kh, n_power));
    return rcpp_result_gen;
END_RCPP
}
// radius_graph_cpp
List radius_graph_cpp(const NumericMatrix& coords, const IntegerVector& sample, const IntegerVector& compartment, double radius, bool same_compartment, bool include_self, std::string weight_method, double weight_scale);
RcppExport SEXP _SpatialESS_radius_graph_cpp(SEXP coordsSEXP, SEXP sampleSEXP, SEXP compartmentSEXP, SEXP radiusSEXP, SEXP same_compartmentSEXP, SEXP include_selfSEXP, SEXP weight_methodSEXP, SEXP weight_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type compartment(compartmentSEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< bool >::type same_compartment(same_compartmentSEXP);
    Rcpp::traits::input_parameter< bool >::type include_self(include_selfSEXP);
    Rcpp::traits::input_parameter< std::string >::type weight_method(weight_methodSEXP);
    Rcpp::traits::input_parameter< double >::type weight_scale(weight_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(radius_graph_cpp(coords, sample, compartment, radius, same_compartment, include_self, weight_method, weight_scale));
    return rcpp_result_gen;
END_RCPP
}
// permute_within_strata_cpp
IntegerVector permute_within_strata_cpp(const IntegerVector& strata, int stratum_count);
RcppExport SEXP _SpatialESS_permute_within_strata_cpp(SEXP strataSEXP, SEXP stratum_countSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type strata(strataSEXP);
    Rcpp::traits::input_parameter< int >::type stratum_count(stratum_countSEXP);
    rcpp_result_gen = Rcpp::wrap(permute_within_strata_cpp(strata, stratum_count));
    return rcpp_result_gen;
END_RCPP
}
// group_tri_mean_dgc_permuted_cpp
NumericMatrix group_tri_mean_dgc_permuted_cpp(const S4& cell_by_gene, const IntegerVector& target_group, const IntegerVector& source_for_target, int group_count);
RcppExport SEXP _SpatialESS_group_tri_mean_dgc_permuted_cpp(SEXP cell_by_geneSEXP, SEXP target_groupSEXP, SEXP source_for_targetSEXP, SEXP group_countSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type cell_by_gene(cell_by_geneSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type target_group(target_groupSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type source_for_target(source_for_targetSEXP);
    Rcpp::traits::input_parameter< int >::type group_count(group_countSEXP);
    rcpp_result_gen = Rcpp::wrap(group_tri_mean_dgc_permuted_cpp(cell_by_gene, target_group, source_for_target, group_count));
    return rcpp_result_gen;
END_RCPP
}
// score_cellchat_group_matrix_cpp
NumericMatrix score_cellchat_group_matrix_cpp(const NumericMatrix& average, const IntegerVector& sender_group, const IntegerVector& receiver_group, const IntegerMatrix& ligand_indices, const IntegerMatrix& receptor_indices, const IntegerMatrix& co_a_indices, const IntegerMatrix& co_i_indices, const IntegerMatrix& agonist_indices, const IntegerMatrix& antagonist_indices, const LogicalVector& has_agonist, const LogicalVector& has_antagonist, double Kh, double n_power);
RcppExport SEXP _SpatialESS_score_cellchat_group_matrix_cpp(SEXP averageSEXP, SEXP sender_groupSEXP, SEXP receiver_groupSEXP, SEXP ligand_indicesSEXP, SEXP receptor_indicesSEXP, SEXP co_a_indicesSEXP, SEXP co_i_indicesSEXP, SEXP agonist_indicesSEXP, SEXP antagonist_indicesSEXP, SEXP has_agonistSEXP, SEXP has_antagonistSEXP, SEXP KhSEXP, SEXP n_powerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type average(averageSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type sender_group(sender_groupSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type receiver_group(receiver_groupSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type ligand_indices(ligand_indicesSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type receptor_indices(receptor_indicesSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type co_a_indices(co_a_indicesSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type co_i_indices(co_i_indicesSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type agonist_indices(agonist_indicesSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type antagonist_indices(antagonist_indicesSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type has_agonist(has_agonistSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type has_antagonist(has_antagonistSEXP);
    Rcpp::traits::input_parameter< double >::type Kh(KhSEXP);
    Rcpp::traits::input_parameter< double >::type n_power(n_powerSEXP);
    rcpp_result_gen = Rcpp::wrap(score_cellchat_group_matrix_cpp(average, sender_group, receiver_group, ligand_indices, receptor_indices, co_a_indices, co_i_indices, agonist_indices, antagonist_indices, has_agonist, has_antagonist, Kh, n_power));
    return rcpp_result_gen;
END_RCPP
}
// spatialess_stream_cpp
List spatialess_stream_cpp(const S4& cell_by_gene, const NumericVector& offsets, const IntegerVector& neighbors, const NumericVector& distances, const IntegerVector& group, int group_count, const IntegerMatrix& ligand_indices, const IntegerMatrix& receptor_indices, const IntegerMatrix& co_a_indices, const IntegerMatrix& co_i_indices, const IntegerMatrix& agonist_indices, const IntegerMatrix& antagonist_indices, const LogicalVector& has_agonist, const LogicalVector& has_antagonist, const LogicalVector& contact_lr, const IntegerMatrix& permutations, double Kh, double n_power, double scale_distance, double contact_threshold, double min_percent, int min_cells_sr, bool use_agan, double max_output_records, double max_active_edges_per_lr);
RcppExport SEXP _SpatialESS_spatialess_stream_cpp(SEXP cell_by_geneSEXP, SEXP offsetsSEXP, SEXP neighborsSEXP, SEXP distancesSEXP, SEXP groupSEXP, SEXP group_countSEXP, SEXP ligand_indicesSEXP, SEXP receptor_indicesSEXP, SEXP co_a_indicesSEXP, SEXP co_i_indicesSEXP, SEXP agonist_indicesSEXP, SEXP antagonist_indicesSEXP, SEXP has_agonistSEXP, SEXP has_antagonistSEXP, SEXP contact_lrSEXP, SEXP permutationsSEXP, SEXP KhSEXP, SEXP n_powerSEXP, SEXP scale_distanceSEXP, SEXP contact_thresholdSEXP, SEXP min_percentSEXP, SEXP min_cells_srSEXP, SEXP use_aganSEXP, SEXP max_output_recordsSEXP, SEXP max_active_edges_per_lrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type cell_by_gene(cell_by_geneSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type offsets(offsetsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type neighbors(neighborsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type distances(distancesSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type group_count(group_countSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type ligand_indices(ligand_indicesSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type receptor_indices(receptor_indicesSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type co_a_indices(co_a_indicesSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type co_i_indices(co_i_indicesSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type agonist_indices(agonist_indicesSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type antagonist_indices(antagonist_indicesSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type has_agonist(has_agonistSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type has_antagonist(has_antagonistSEXP);
    Rcpp::traits::input_parameter< const LogicalVector& >::type contact_lr(contact_lrSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type permutations(permutationsSEXP);
    Rcpp::traits::input_parameter< double >::type Kh(KhSEXP);
    Rcpp::traits::input_parameter< double >::type n_power(n_powerSEXP);
    Rcpp::traits::input_parameter< double >::type scale_distance(scale_distanceSEXP);
    Rcpp::traits::input_parameter< double >::type contact_threshold(contact_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type min_percent(min_percentSEXP);
    Rcpp::traits::input_parameter< int >::type min_cells_sr(min_cells_srSEXP);
    Rcpp::traits::input_parameter< bool >::type use_agan(use_aganSEXP);
    Rcpp::traits::input_parameter< double >::type max_output_records(max_output_recordsSEXP);
    Rcpp::traits::input_parameter< double >::type max_active_edges_per_lr(max_active_edges_per_lrSEXP);
    rcpp_result_gen = Rcpp::wrap(spatialess_stream_cpp(cell_by_gene, offsets, neighbors, distances, group, group_count, ligand_indices, receptor_indices, co_a_indices, co_i_indices, agonist_indices, antagonist_indices, has_agonist, has_antagonist, contact_lr, permutations, Kh, n_power, scale_distance, contact_threshold, min_percent, min_cells_sr, use_agan, max_output_records, max_active_edges_per_lr));
    return rcpp_result_gen;
END_RCPP
}
// benchmark_sparse_type7_cpp
List benchmark_sparse_type7_cpp(const NumericVector& positive_values, int total_count, int iterations);
RcppExport SEXP _SpatialESS_benchmark_sparse_type7_cpp(SEXP positive_valuesSEXP, SEXP total_countSEXP, SEXP iterationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type positive_values(positive_valuesSEXP);
    Rcpp::traits::input_parameter< int >::type total_count(total_countSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    rcpp_result_gen = Rcpp::wrap(benchmark_sparse_type7_cpp(positive_values, total_count, iterations));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SpatialESS_group_tri_mean_dgc_cpp", (DL_FUNC) &_SpatialESS_group_tri_mean_dgc_cpp, 3},
    {"_SpatialESS_aggregate_group_support_csr_cpp", (DL_FUNC) &_SpatialESS_aggregate_group_support_csr_cpp, 6},
    {"_SpatialESS_score_cellchat_group_support_cpp", (DL_FUNC) &_SpatialESS_score_cellchat_group_support_cpp, 17},
    {"_SpatialESS_radius_graph_csr_cpp", (DL_FUNC) &_SpatialESS_radius_graph_csr_cpp, 9},
    {"_SpatialESS_validate_spatial_csr_cpp", (DL_FUNC) &_SpatialESS_validate_spatial_csr_cpp, 6},
    {"_SpatialESS_materialize_csr_edges_cpp", (DL_FUNC) &_SpatialESS_materialize_csr_edges_cpp, 4},
    {"_SpatialESS_csr_weighted_degree_cpp", (DL_FUNC) &_SpatialESS_csr_weighted_degree_cpp, 2},
    {"_SpatialESS_aggregate_simple_lr_csr_cpp", (DL_FUNC) &_SpatialESS_aggregate_simple_lr_csr_cpp, 11},
    {"_SpatialESS_score_simple_lr_edge_cpp", (DL_FUNC) &_SpatialESS_score_simple_lr_edge_cpp, 10},
    {"_SpatialESS_score_cellchat_group_records_cpp", (DL_FUNC) &_SpatialESS_score_cellchat_group_records_cpp, 14},
    {"_SpatialESS_radius_graph_cpp", (DL_FUNC) &_SpatialESS_radius_graph_cpp, 8},
    {"_SpatialESS_permute_within_strata_cpp", (DL_FUNC) &_SpatialESS_permute_within_strata_cpp, 2},
    {"_SpatialESS_group_tri_mean_dgc_permuted_cpp", (DL_FUNC) &_SpatialESS_group_tri_mean_dgc_permuted_cpp, 4},
    {"_SpatialESS_score_cellchat_group_matrix_cpp", (DL_FUNC) &_SpatialESS_score_cellchat_group_matrix_cpp, 13},
    {"_SpatialESS_spatialess_stream_cpp", (DL_FUNC) &_SpatialESS_spatialess_stream_cpp, 25},
    {"_SpatialESS_benchmark_sparse_type7_cpp", (DL_FUNC) &_SpatialESS_benchmark_sparse_type7_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_SpatialESS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
